### PR TITLE
Create_headers_and_footers.rst

### PR DESCRIPTION
**Pull request by bradchesney79**
Thank you for contributing! Please follow the guidelines below to submit your
pull request. Additional details are available in our
[Contributor Guide](https://docs.coderedcorp.com/cms/stable/contributing/index.html).

#### Description of change
Explain what you changed, and how or why it works the way it does.

Just written down the steps to editing the existing header snippet and adding a footer snippet.

#### Documentation
Should be added to the `docs/` directory. If you're not sure how to add
documentation, please provide a description here instead.

Add to docs directory-- check.

#### Tests
Unit tests should be included to test your changes. If you're not sure how to
write unit tests, please provide a description of how to test this change
manually.

N/A

### CODE REVIEW

**Comment by bradchesney79** [comment]
... I changed one file that doesn't actually do anything. Not sure why it failed any tests.

(Details notes Powershell & Azure issues, typical.)

**Comment by vsalvino** [comment]
Thanks for the contribution! Doc additions are always welcome and much needed.

Looks like sphinx is complaining about the underline length being shorter than the title (Sorry, I know the CI output is difficult to read): https://dev.azure.com/coderedcorp/coderedcms/_build/results?buildId=967&view=logs&j=575c5b88-07eb-539a-cb33-aa68f7fb9baa&t=3a1a6c97-b7a0-57b6-18a8-db4e6ddaafc6&l=76

**Comment by bradchesney79** [comment]
Added more equal sign characters to align with the title.
Then also added the filename to the toc.

**Comment by vsalvino** [comment]
I will merge this in, and then do some editing. Thanks!

**Pull request merged**
