### PR TITLE
Remove as much custom CSS as possible from the Wagtail admin

### PR DESCRIPTION
**Pull request by vsalvino**
* Remove as much of our custom CSS as possible, to reduce maintenance burden. This includes anything mildly opinionated, such as font styles, and anything that was used to fix previous accessibility issues in Wagtail which are no longer prevalent (e.g. light gray on white form inputs).
* Unfortunately most of the grisly CSS is still needed to make our nested streamfields usable. We should hopefully be able to remove nearly all of it with the UI changes coming in Wagtail 3.0.
* Fix showing the site logo in the wagtail admin for 2.16
* Remove our "powered by CodeRed" logo

Tested manually by spot-checking various areas of the Wagtail Admin.

### CODE REVIEW

**Comment by jlchilders11** [comment]
The icons on our blocks seem to no longer be present. This may have been broken in a different PR, but we should probably fix it while updating the css.

**Comment by vsalvino** [comment]
Seems like the icon breakage is related to the Wagtail 2.15/16 upgrade. Asked for more details here: https://github.com/wagtail/wagtail/issues/8533

**Comment by vsalvino** [comment]
Logged a separate issue, since that bug is present in the dev branch: #484

**Comment by FlipperPA** [comment]
@vsalvino I just have to say, this looks like it was **REALLY** fun to do! 🥇

**Comment by vsalvino** [comment]
@FlipperPA the real fun is yet to come with Wagtail 3.0 (although it will be most fun if I get to delete the entire file)

**Pull request merged**
